// Auto-generated by scripts/build-tweakcn-themes.mjs
export const tweakcnThemes = [
    {
        name: "amber-minimal",
        title: "Amber Minimal",
    },
    {
        name: "amethyst-haze",
        title: "Amethyst Haze",
    },
    {
        name: "bold-tech",
        title: "Bold Tech",
    },
    {
        name: "bubblegum",
        title: "Bubblegum",
    },
    {
        name: "caffeine",
        title: "Caffeine",
    },
    {
        name: "candyland",
        title: "Candyland",
    },
    {
        name: "catppuccin",
        title: "Catppuccin",
    },
    {
        name: "claude",
        title: "Claude",
    },
    {
        name: "clean-slate",
        title: "Clean Slate",
    },
    {
        name: "cosmic-night",
        title: "Cosmic Night",
    },
    {
        name: "darkmatter",
        title: "Darkmatter",
    },
    {
        name: "graphite",
        title: "Graphite",
    },
    {
        name: "kodama-grove",
        title: "Kodama Grove",
    },
    {
        name: "mocha-mousse",
        title: "Mocha Mousse",
    },
    {
        name: "modern-minimal",
        title: "Modern Minimal",
    },
    {
        name: "mono",
        title: "Mono",
    },
    {
        name: "nature",
        title: "Nature",
    },
    {
        name: "neo-brutalism",
        title: "Neo Brutalism",
    },
    {
        name: "northern-lights",
        title: "Northern Lights",
    },
    {
        name: "notebook",
        title: "Notebook",
    },
    {
        name: "pastel-dreams",
        title: "Pastel Dreams",
    },
    {
        name: "perpetuity",
        title: "Perpetuity",
    },
    {
        name: "quantum-rose",
        title: "Quantum Rose",
    },
    {
        name: "retro-arcade",
        title: "Retro Arcade",
    },
    {
        name: "soft-pop",
        title: "Soft Pop",
    },
    {
        name: "solar-dusk",
        title: "Solar Dusk",
    },
    {
        name: "starry-night",
        title: "Starry Night",
    },
    {
        name: "sunset-horizon",
        title: "Sunset Horizon",
    },
    {
        name: "supabase",
        title: "Supabase",
    },
    {
        name: "t3-chat",
        title: "T3 Chat",
    },
    {
        name: "tangerine",
        title: "Tangerine",
    },
    {
        name: "twitter",
        title: "Twitter",
    },
    {
        name: "vercel",
        title: "Vercel",
    },
    {
        name: "vintage-paper",
        title: "Vintage Paper",
    },
    {
        name: "violet-bloom",
        title: "Violet Bloom",
    },
] as const

export type TweakcnTheme = (typeof tweakcnThemes)[number]["name"]
